import "./globals.css";
import Navbar from "@/components/layout/Navbar";

export const metadata = {
  title: "MyTeacher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-accent-50">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
